{% set version = "1.1.0" %}

package:
  name: transformato
  version: 0.3

source:
  url: https://github.com/wiederm/transformato/archive/refs/tags/v0.3.tar.gz
  sha256: 00a8b8ac33a49a179035fc2ace86c382bad0f94363d95a7aa6a0f0157c181156
  
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv   

requirements:
  host:
  - pip
  - python >=3.6
  run:
  - python >=3.6
  - openmm
  - openmmtools
  - numpy
  - ipython
  - pymbar =3
  - rdkit
  - parmed
  - pyyaml
  - mdtraj
  - mdanalysis
  - matplotlib-base
  - networkx
  - tqdm
  - seaborn
  - pytest
  - pytest-cov
  - codecov

test:
  imports:
    - transformato
    - transformato.mutate
    - transformato.analysis
    - transformato.constants
    - transformato.restraints
    - transformato.state
    - transformato.system
    - transformato.utils
        
about:
  home: https://github.com/wiederm/transformato
  summary: 'Tool for setting up relativ binding free energyies'
  description: |
    Transformato is a tool which creates files for mutating
    one ligand into another (relative binding free energy).
    The created files are used to run MD simulations and calculate
    the resulting free energy differences.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://wiederm.github.io/transformato/

extra:
  recipe-maintainers:
    - wiederm
    - JohannesKarwou
