---
################
system:
################
  structure1:
    name:
      '2OJ9-test1'
    tlc:
      'BMI'
    vacuum:
      dirname:
        'vacuum'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_vacuum'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

  structure2:
    name:
      '2OJ9-test2'
    tlc:
      'UNK'
    vacuum:
      dirname:
        'vacuum'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_vacuum'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

################
simulation:
################
  parameters:
    nstep:
      5000
    nstdcd:
      50
    nstout:
      50
    cons:
      None
    dt:
      0.001

  free-energy-type:
    'solvation-free-energy'
################
solvation:
################
  steps_for_equilibration:
    1000


  

  