---
################
system:
################
  structure1:
    name:
      'toluene'
    tlc:
      'UNL'
    vacuum:
      dirname:
        'vacuum'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_vacuum'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

  structure2:
    name:
      'methane'
    tlc:
      'LIG'
    vacuum:
      dirname:
        'vacuum'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_vacuum'
    waterbox:
      dirname:
        'waterbox'
      psf_file_name:
        'step3_charmm2omm'
      crd_file_name:
        'step3_charmm2omm'
      rst_file_name:
        'step4_equilibration'
      simulation_parameter:
        'step5_production.inp'
      intermediate-filename:
        'lig_in_waterbox'

################
simulation:
################
  parameters:
    nstep:
      250000
    nstdcd:
      5000
    nstout:
      5000
  free-energy-type:
    'solvation-free-energy'
################
solvation:
################
  steps_for_equilibration:
    1000


  

  
