name: Black formatting

on: [push, pull_request]


permissions:
  checks: write
  contents: write 
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
