name: Black formatting

on: [pull_request]


permissions:
  checks: write
  contents: write 
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          black_args: '--extend-exclude="(bin/*|scripts/*|_version.py)"'
      
