name: Pytest restraints

on:
  push:
    branches:
      - "restraints"


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file devtools/conda-envs/test_env.yaml --name test

        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
        
    - name: Test with pytest
      run: |
        conda install pytest
        pytest -v -m restraints --cov=transformato.restraints
